{% set pyproject = load_file_data('pyproject.toml') %}

# It was not possible to set name and version from pyproject.toml.
{% set name = "nodimo" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

about:
  license: MIT
  license_file: {{ pyproject.get('project').get('license').file }}
  license_url: https://github.com/rodrigopcastro018/nodimo/blob/main/LICENSE
  Home: {{ pyproject.get('project').get('urls').Source }}
  dev_url: {{ pyproject.get('project').get('urls').Source }}
  doc_url: {{ pyproject.get('project').get('urls').Documentation }}
  summary: {{ pyproject.get('project').get('description') }}
  description: >
    The main purpose of Nodimo is to transform a dimensional relationship
    between quantities into a dimensionless one. This is done by grouping
    dimensional quantities into dimensionless products in such a way that
    the resulting number of products is always lower than or equal to the
    starting number of quantities. Therefore, the ensuing dimensionless
    model is, at the same time, a generalization and simplification of the
    dimensional model.

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18d996bccf816b6f45e6769d9c131c084528321b913707eb02b65b5bae6c5e41
  md5: cf7711ee935e322aff0764fb1a258fc3

requirements:
  host:
    - pip
    - python>=3.9
  run:
    - python>=3.9
    - sympy>=1.7

build:
  script: {{ PYTHON }} -m pip install . -vv

extra:
  recipe-maintainers:
    - rodrigopcastro018
