name: Basic Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Nodimo
        run: python -m pip install -e .[test]

      - name: Run pytest
        run: pytest
      
      - name: Run mypy
        run: mypy
