name: Fast Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  
  test:
    name: Quick test on latest dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Nodimo and test dependencies
        run: python -m pip install -e .[test]

      - name: Create folder for tests
        run: mkdir test_results
      
      - name: Run pytest and save result
        run: pytest -q | tee test_results/pytest_result.txt
      
      - name: Save coverage result
        run: coverage report > test_results/coverage_result.txt
      
      - name: Run mypy and save result
        run: mypy | tee test_results/mypy_result.txt

      - name: Output test summary
        run: |
          echo "| **Case** | mypy | pytest | coverage |" >> $GITHUB_STEP_SUMMARY
          echo "| :------- | :--: | :----: | :------: |" >> $GITHUB_STEP_SUMMARY
          python .github/fast_test_summary.py linux-latest_dependencies
