name: Fast Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  
  tests:
    name: Quick test on latest dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install nodimo and test dependencies
        run: python -m pip install -e .[test]

      - name: Run pytest and save result
        run: python -m pytest -q --junit-xml=tests_results/results-Linux-latest_dependencies/pytest_result.xml

      - name: Save coverage result
        run: coverage json -o tests_results/results-Linux-latest_dependencies/coverage_result.json

      - name: Run mypy and save result
        run: mypy --junit-xml tests_results/results-Linux-latest_dependencies/mypy_result.xml

      - name: Create summary
        if: always()
        run: python3 .github/tests_summary.py
