name: Full Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  tests:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        py:
          - python: '3.9'
            sympy: '1.7'
          - python: '3.12'
            sympy: '1.12'
      fail-fast: false

    name: ${{ matrix.os }}-py${{ matrix.py.python }}-sp${{ matrix.py.sympy }}
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py.python }}
      
      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox
        env:
          CONTEXT: ${{ runner.os }}-py${{ matrix.py.python }}-sp${{ matrix.py.sympy }}
          SYMPY_VERSION: ${{ matrix.py.sympy }}

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ runner.os }}-py${{ matrix.py.python }}
          path: .coverage

      - name: Store results folder
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ runner.os }}-py${{ matrix.py.python }}-sp${{ matrix.py.sympy }}
          path: tests_results

  merge_tests_results:
    name: Merge tests results
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Merge tests results
        uses: actions/upload-artifact/merge@v4
        with:
          name: tests_results
          pattern: results-*
          delete-merged: true

  create_summary:
    name: Table
    needs: merge_tests_results
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download tests results
        uses: actions/download-artifact@v4
        with:
          name: tests_results
          path: tests_results
    
      - name: Create summary
        run: python3 .github/tests_summary.py

  merge_coverage:
    name: Merge coverage
    needs: tests
    runs-on: ubuntu-latest

    steps:

      - name: Merge coverage
        uses: actions/upload-artifact/merge@v4
        with:
          name: coverage
          pattern: coverage-*
          delete-merged: true

  combine_coverage:
    name: Combine coverage
    needs: merge_coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download coverage files
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .coverage
      
      - name: Install coverage
        run: pip install coverage[toml]
      
      - name: Coverage combine
        run: coverage combine .coverage
      
      - name: Generate combined coverage HTML
        run: coverage html --show-contexts --title "Coverage for ${{ github.sha }}"

      - name: Store combined coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage_html
          path: .coverage/htmlcov

  smokeshow_coverage:
    name: Smokeshow coverage
    needs: combine_coverage
    runs-on: ubuntu-latest

    permissions:
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download coverage HTML
        uses: actions/download-artifact@v4
        with:
          name: coverage_html
          path: .coverage/htmlcov
      
      - name: Install smokeshow
        run: pip install smokeshow
      
      - name: Smokeshow coverage HTML
        run: smokeshow upload .coverage/htmlcov
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 100
          SMOKESHOW_GITHUB_CONTEXT: coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.sha }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
