name: Smokeshow

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

permissions:
    statuses: write

jobs:

  smokeshow-coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install smokeshow
        run: pip install smokeshow


      - name: Download coverage HTML
        uses: actions/download-artifact@v4
        with:
          name: coverage_html
          path: coverage/htmlcov

      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: test.yml
          commit: ${{ github.event.workflow_run.head_sha }}

      - name: Smokeshow coverage HTML
        run: smokeshow upload coverage/htmlcov
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 100
          SMOKESHOW_GITHUB_CONTEXT: coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
