name: Test

on: [push, pull_request]

jobs:
  
  test:

    strategy:
      matrix:
        os: [windows-latest]
        include:
          - python-version: '3.9'
            numpy-version: '1.20.0'
            sympy-version: '1.7'
          - python-version: '3.12'
            numpy-version: '1.26.4'
            sympy-version: '1.12'
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install tox
        run: python -m pip install --user tox

      - name: Run tox
        run: tox
        env:
          INITIAL_CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}
          NUMPY_VERSION: ${{ matrix.numpy-version }}
          SYMPY_VERSION: ${{ matrix.sympy-version }}

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ runner.os }}-py${{ matrix.python-version }}
          path: coverage

  merge_coverage:

    name: Merge Coverage
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Merge Coverage
        uses: actions/upload-artifact/merge@v4
        with:
          name: coverage
          pattern: coverage-*
          delete-merged: true

  combine_coverage:

    name: Combine Coverage
    needs: merge_coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download coverage files
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage
      
      - name: Install coverage
        run: pip install coverage[toml]
      
      - name: Coverage combine
        run: coverage combine coverage
      
      - name: Generate combined coverage HTML
        run: coverage html --show-contexts --title "Coverage for ${{ github.sha }}"

      - name: Store combined coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage_html
          path: coverage/htmlcov
