name: Test

on: [push, pull_request]

jobs:
  test:

    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.11", "3.12"]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Install Nodimo
        run: python -m pip install -e .

      - name: Install test dependencies
        run: python -m pip install .[test]
      
      - name: Run pytest
        run: pytest

        env:
          COVERAGE_FILE: coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}
          CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage.${{ runner.os }}-py${{ matrix.python-version }}
          path: coverage

  # coverage-combine:
  #   needs: