name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.0", "3.12.0"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install test dependencies
        run: python -m pip install .[test]
      
      - name: Run pytest
        run: pytest
      
      - name: Upload coverage html files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/cov_html